# ingress configuration
ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/issuer: letsencrypt-openfaas-prod
    tls:
      - hosts:
          - <FQDN for openfaas gateway>
        secretName: openfaas-crt
    hosts:
      - host: <FQDN for openfaas gateway>
        serviceName: gateway
        servicePort: 8080
        path: /
